### ISSUE TITLE
[BUG] Can't use syntax after reload aliases

### ISSUE THREAD

**Issue by sj-hub9796** [ShaneBeee/SkArclight#1]
### What happened?

SkArclight's syntax throws an error

### Steps to reproduce

1. enter the command "/sk reload aliases"
2. and "/sk reload (your scripts).sk"

### Expected behavior

skarclight's aliases must also be reloaded.

### SkArclight Version

1.0.0

### Skript Version

2.7.3

### Server Version

arclight-1.20.1-1.0.4

### Additional Information

I'm using farmers delight

**Comment by ShaneBeee** [comment]
Were you going to provide the error?

**Comment by sj-hub9796** [comment]
> Were you going to provide the error?

uh, i wanted to let you know that there was an error.

**Comment by ShaneBeee** [comment]
and what is the error?

**Comment by sj-hub9796** [comment]
> SkArclight's syntax throws an error

okay, give me seconds. let me show you video

**Comment by sj-hub9796** [comment]
> and what is the error?

https://github.com/ShaneBeee/SkArclight/assets/130253873/b236be6d-a1c1-45de-92da-aa62d7a856b7

**Comment by ShaneBeee** [comment]
Ok, next question... why exactly are you reloading aliases?

**Comment by sj-hub9796** [comment]
> Ok, next question... why exactly are you reloading aliases?

Sometimes I reload by mistake... XD
So I always have to restart the server, which is a bit annoying.

**Comment by ShaneBeee** [comment]
then don't... SkArclight creates modded aliases when the plugin loads.
When you reload aliases, Skript is wiping all aliases and starting again... Therefor all modded aliases have been wiped.

**Comment by sj-hub9796** [comment]
> then don't... SkArclight creates modded aliases when the plugin loads.
> When you reload aliases, Skript is wiping all aliases and starting again... Therefor all modded aliases have been wiped.

haha, alright. thank you for response. i'll close this issue
