### ISSUE TITLE
[SUGGESTION] Support Mohist bukkit

### ISSUE THREAD

**Issue by Ru-Nan-i** [ShaneBeee/SkArclight#2]
### Suggestion

Can I use this addon in Mohist?
If it's not available, please support it.

### Alternatives

It would be nice to use this addon available in mohist

**Comment by sj-hub9796** [comment]
try and see it, also works fine on other hybrids.

**Comment by ShaneBeee** [comment]
I just loaded SkArclight with Mohist, using the mod TFC (TerraFirmaCraft)

# Some results:
## loading:
<img width="525" alt="Screenshot 2024-11-11 at 11 18 37 AM" src="https://github.com/user-attachments/assets/2b5bf073-c3ed-4f0a-ab7e-1ddac1d34601">

## Testing with an item:
<img width="380" alt="Screenshot 2024-11-11 at 11 18 57 AM" src="https://github.com/user-attachments/assets/d854acf3-a19c-4324-bbf2-b279b06a2930">

## Testing with a block data:
(This is a Skript thing, not SkArclight, but just wanted to show it off)
<img width="616" alt="Screenshot 2024-11-11 at 11 20 06 AM" src="https://github.com/user-attachments/assets/7fa6b91f-f7e8-432a-a1f3-1e1c36bf3982">

## Testing with `mod entity type of %entity%`:
<img width="616" alt="Screenshot 2024-11-11 at 11 24 21 AM" src="https://github.com/user-attachments/assets/3d1e870f-b2d6-4fd6-b8be-bef6e3a18b94">

Needless to say, it appears to work on Mohist.

as sj stated, I guess you could have tried it and seen that it works.

Closing as there is no issue here.
