### ISSUE TITLE
[SUGGESTION] Add other play sound effect for mod sounds

### ISSUE THREAD

**Issue by ElgerElg** [ShaneBeee/SkArclight#8]
### Suggestion

ShaneBee writes about this in Pull requests. I think it's very useful effect because original Skript (my ver. is 2.9.3) can't play sound from mods

### Alternatives

skRayFall but it's old and buggy. https://skripthub.net/docs/?id=67

**Comment by ShaneBeee** [comment]
As I already stated in the PR, it was a bug with Skript, that has been fixed, the fix will appear in Skript 2.10

**Comment by ElgerElg** [comment]
But... This fix is only for newer version. I use 1.16.5 ver and 2.9.2 skript :(
